# Site settings
name: Imad MAROUF
title: Imad MAROUF | EE/CS Engineer
description: Engineering Student
url: https://iemprog.github.io/
baseurl: ''
email: imad.marouf@etu.upmc.fr
cover: https://iemprog.github.io/img/og.png
logo: https://iemprog.github.io/img/emojis/technologist.png
resume: https://bchiang7.github.io/resume.pdf
social:
  - title: email
    url: mailto:imad.marouf@etu.upmc.fr
  - title: twitter
    url: https://twitter.com/IemProg
  - title: github
    url: https://github.com/IemProg
  - title: linkedin
    url: https://www.linkedin.com/in/iemprog

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
